### ISSUE TITLE
Desktop v1.7.0 doesn't seem to load properly on latest version of Windows 11

### ISSUE THREAD

**Issue by toddwalden** [Droplr/droplr-desktop-releases#2]
After installing, I only see the Droplr logo spinning animation until I click somewhere on my desktop. After that, if I try clicking the Droplr icon in the taskbar, I just see a white box.

My machine:
Windows 11 Pro v10.0.22631

https://github.com/Droplr/droplr-desktop-releases/assets/364519/28afbc1d-740a-4e2e-bf1b-cc9863cb10ed

**Comment by harismuha123** [comment]
@toddwalden Hi! We're currently working on a fix for this issue, it has been happening on Windows 10 machines mostly, a new version is being QA'd as we speak. If you want, you can check out the pre-release 1.7.1, it's available in our releases. If that doesn't fix it, the best way of resetting the app to default settings is to delete it completely from the installation folder, including the storage dump that is saved in AppData, and to reinstall it from scratch. That should hopefully solve the issue.

**Comment by toddwalden** [comment]
@harismuha123 ahh ok yep, deleting the folders in AppData and reinstalling the latest version fixed it for me! Thanks so much. I've been a Droplr user for years now and can't live without it. Thanks again for making it better and better!

**Comment by harismuha123** [comment]
@toddwalden thank you so much for the kind words! We appreciate your feedback very much and are glad you reached out. Whatever you have for us, either problems or suggestions, feel free to contact us here or via email, we'll be happy to improve the product even more.
